version: "3.8"
services:
  redis-server:
    container_name: redis-server
    image: redis:6.2.6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
